// AUTO-GENERATED from resources/icon.png in bh-minecraft-launcher.
// Block pixel art; regenerate with scripts/gen-logo-art.py.

export interface LogoArt {
  /** Width/height of the square pixel grid. */
  size: number
  /** `size` rows of `size` base64 chars indexing LOGO_PALETTE. */
  rows: string[]
}

export const LOGO_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
export const LOGO_PALETTE = [
  "#181825", // transparent (panel bg)
  "#403854", // cube face 1
  "#685782", // cube face 2
  "#967bb4", // cube face 3
  "#bea3e4", // cube face 4
  "#cdd6f4", // BH letters
]

export const BLOCKHAVEN_LOGO: Record<number, LogoArt> = {
  8: {
    size: 8,
    rows: [
      "AACCCCCA",
      "BCDDDDCA",
      "CFFFFFCA",
      "BFFFFFCA",
      "BFFFFFCA",
      "BCFCCCCA",
      "BCCCCCBA",
      "AAAAAAAA",
    ],
  },
  12: {
    size: 12,
    rows: [
      "AAAAABBABABA",
      "AACDDDDDDDCA",
      "ACCCCDDDDCBA",
      "BFFFFFFCFCCA",
      "ACFFFFFCFCCA",
      "ACFFFCFFFCBA",
      "ACFCFFFFFBBA",
      "ACFFFFFCFBBA",
      "BCCCCCBCCCBA",
      "BCFFCCFFCCAA",
      "ACCCBBCCCBAA",
      "AAAAAAAAAAAA",
    ],
  },
  16: {
    size: 16,
    rows: [
      "AAAAAAAAAAAAAAAA",
      "AAABDCCDCCCDCDCA",
      "AACDDDDDDDDDDCBA",
      "ACCCCCCDDDDDCCBA",
      "ACFFFFCDCCCDCCBA",
      "ACFFFFFCFCFFCCCA",
      "ACFFAFFCFBFFCBBA",
      "ACCFFFFCFFFFCBBA",
      "ACFFBCFFFFFFBCBA",
      "ACFFFFFFFBFFBBBA",
      "ACCFFFBBFBFBCCBA",
      "ACCBCCCCACCCCBBA",
      "ACCFFCCCFFCCCBAA",
      "ACCCCCCCCCCCBAAA",
      "AAABBABBBBABAAAA",
      "AAAAAAAAAAAAAAAA",
    ],
  },
  20: {
    size: 20,
    rows: [
      "AAAAAAAAAAAAAAAAAAAA",
      "AAAAACCCCCCCCCCCCCBA",
      "AAABDDDDDDDDDDDDDCAA",
      "AACDDCDDDDDDDDDDBBBA",
      "ACDCCFCCCDDDDDDCCCBA",
      "ACCFFFCCCDCCCCCCFCAA",
      "ACCFFFFFFCFFCFFCCCBA",
      "ACCFFBCFFCFCCFFCCFBA",
      "ABCFFCCFCCFFCFFCBBAA",
      "ACCFFFFFCCFFFFFCBCBA",
      "ACCFFFBFFFFFFFFBFBAA",
      "ACBFFBBFFFFCBFFBBBBA",
      "ACBFFFFFFCFCCFFBCBBA",
      "ACCCCCFBBBFBBFACCBAA",
      "ACCBCCCCCCABCCCCBBAA",
      "ACCCFFCDCCFFFCCCBBAA",
      "ACDDCCCCCCFFCDCBBAAA",
      "ABCCCCCCCCCDCCCCAAAA",
      "AAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAA",
    ],
  },
  24: {
    size: 24,
    rows: [
      "AAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAABBBBCCCCBCCCBBBBAA",
      "AAAAACDDDDDDDDDCDDDDDCAA",
      "AAABDDDCCDDDDDDDDDDDBBAA",
      "AACDCCCDDDDDCDDDDCCBBBAA",
      "ACDCCCFCCCCDDDDCDDCCCBAA",
      "ACDCFFCCCCDDCCCCCCCCFBAA",
      "ABCFFFFFFFCCFFBFFFCBCBBA",
      "ACDCFFFFFFCCFFAFFFCCCFAA",
      "ABCCFFAAFFCCFFAFFFCCBCAA",
      "AACCFFFDFFACFFCFFFFBBBAA",
      "ABDCFFFFFFCFFFFFFFCBCCAA",
      "ACCCFFFBFFFFFFFFFFAFCBAA",
      "ABCCFFAACFFFFFAFFFBBBBAA",
      "ACCCFFFFFFFFFFAFFFBCBBBA",
      "ABCCFFFFFFACFFAFFBBCBBAA",
      "ABCCABABBBCBBBBBBBCCBBAA",
      "ACDCBCCCCCCCBBCCCDCBCBAA",
      "ABCCCFFFCDCCFFFFCDCBBBAA",
      "ACDDCCCCDCCCFFCCCCBBAAAA",
      "ABCCCCCCCCCCCCDDDCCAAAAA",
      "AABBCCCBBCCCCCCBBBBAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAA",
    ],
  },
  32: {
    size: 32,
    rows: [
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAACDCDCCDDDDCCCDDDCCCCCCAA",
      "AAAAAAACDDDDDDCCCCDDCCDDDDDDCBAA",
      "AAAAACDDDCCCCDDDDDCDDDDDDECBBBAA",
      "AAABDDDCCCDDDDDDDDDDDEDDDCBBCBAA",
      "AACDDCCCCCDDCCDDCCDCCDCCCBABBBAA",
      "AADDCCCCFDCCCCDDDDDDDDDDCBFCBBAA",
      "AADDBFFBCBBBCDDDDCCCCCCCDBFCBAAA",
      "AACCFFFFFFFFFCCFCCCCCCFCCCBCBBAA",
      "AACDBFFFFFFFFFAFFFFAFFFFCCCCBBAA",
      "AADDCFFFFFFFFFAFFFFAFFFFCCCCFBAA",
      "AACDCFFFCABFFFAFFFFAFFFFCCBCFAAA",
      "AACCBFFFCACFFFACFFFAFFFFCCBBBAAA",
      "AABCCCFFFFFFFAAFFFFFFFFFFBABCBAA",
      "AACDCCFFFFFFFFAFFFFFFFFFBBCCCBAA",
      "AACCAFFFFFFFFFFFFFFFFFFFACFBBAAA",
      "AACCBFFFCAAFFFFFFFFAFFFFBBCBBBAA",
      "AACCBFFFBAAFFFFFFFFAFFFFBBBBABAA",
      "AACBBFFFFFFFFFFFFFFAFFFFBCCBABAA",
      "AACCBFFFFFFFFBAFFFCAFFFABCBACAAA",
      "AACCCBCFFFFBABBBFFBBFFBABCFBBAAA",
      "AADDDBAAAABCCCCCAAABBABCCBBBBBAA",
      "AACCCCCCFCCDCCCCCBCCCCDDCBCBAAAA",
      "AACBCBFFFFCCDDCCCCFFFBCDCCCBBAAA",
      "AADDDDCFFCCDDCCCFFFFCCCCCABABAAA",
      "AACCCDCCCCDCCCBBCCCCDDCCCBBAAAAA",
      "AACCCCCCDCCCBBBCCCDDDDCCCBAAAAAA",
      "AABBBCCCCCBBCCCCCCCCBBBCCAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ],
  },
}
